version: '3.6'

services:

  order-service:
    container_name: order-service
    image: order-service:latest
    build:
      context: ./order-service
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      MONGO_URL: ''
      MONGO_DATABASE: 'ecommerce'
      SQS_PROCESSED_ORDERS_QUEUE: ''
      SNS_ORDERS_TOPIC: ''

  payment-service:
    container_name: payment-service
    image: payment-service:latest
    ports:
      - 8081:8081
    

  inventory-service:
    container_name: inventory-service
    image: inventory-service:latest
    ports:
      - 8082:8082

