spring:
  application:
    name: payment-service
  data:
    mongodb:
      uri: mongodb://root:root@localhost
      database: payments

aws:
  region: us-east-1
  sqs:
    endpoint: ${ORDERS_QUEUE}
  sns:
    processed-orders-topic: ${PROCESSED_ORDERS_TOPIC}

server:
  port: 8081