server:
  port: ${PORT}

spring:
  application:
    name: order-service
  data:
    mongodb:
      uri: ${MONGO_URL}
      database: ${MONGO_DATABASE}

aws:
  region: us-east-1
  sqs:
    endpoint: ${SQS_PROCESSED_ORDERS_QUEUE}
  sns:
    orders-topic: ${SNS_ORDERS_TOPIC}